[package]
name = "margin_liquidation"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
deepbook_margin = { local = "../deepbook_margin" }

# Pyth dependency
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "main" }

[addresses]
margin_liquidation = "0x0"
