[package]
name = "test_swap"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "main" }

[addresses]
test_swap = "0x0"
