[package]
name = "test_swap"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
token = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/token", rev = "main"}
deepbook = { local = "../deepbook" }

[addresses]
test_swap = "0x0"
