[package]
name = "deepbook_margin"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
token = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/token", rev = "main"}
deepbook = { local = "../deepbook" }

# Pyth dependency
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "main" }

[addresses]
deepbook_margin = "0x0"
