name: Deploy DeepBook Services

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - crates/**
      - docker/**
      - Cargo.lock
      - Cargo.toml

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  deploy-pulumi:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Pulumi Deployment
        uses: mheap/pin-github-action@v2
        with:
          repo: peter-evans/repository-dispatch
          version: v3
          uses-args: |
            repository: MystenLabs/sui-operations
            token: ${{ secrets.DEPLOY_PULUMI_DISPATCH_TOKEN }}
            event-type: pulumi-up
            client-payload: |-
              {
                  "project_path": "apps/deepbook",
                  "stack_to_update": "testnet"
              }

      - name: View deployment status
        run: |
          echo "ðŸš€ View the status of the deployment here: https://github.com/MystenLabs/sui-operations/actions/workflows/pulumi-up.yaml"
    